"""add parent_run_id to scenario_runs

Revision ID: 6520e1c6b594
Revises: 91222e284d25
Create Date: 2026-09-29 17:18:21.947256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.app.models.base import GUID
import backend.app.models.base


# revision identifiers, used by Alembic.
revision: str = '6520e1c6b594'
down_revision: Union[str, None] = '91222e284d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_runs', sa.Column('parent_run_id', backend.app.models.base.GUID(length=36), nullable=True))
    op.create_index(op.f('ix_scenario_runs_parent_run_id'), 'scenario_runs', ['parent_run_id'], unique=False)
    op.create_foreign_key(None, 'scenario_runs', 'scenario_runs', ['parent_run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenario_runs', type_='foreignkey')
    op.drop_index(op.f('ix_scenario_runs_parent_run_id'), table_name='scenario_runs')
    op.drop_column('scenario_runs', 'parent_run_id')
    # ### end Alembic commands ###
