"""add_typed_fields_to_scenario_assumptions

Revision ID: 91222e284d25
Revises: e7cf957617be
Create Date: 2026-09-29 10:42:40.183021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.app.models.base import GUID
import backend.app.models.base


# revision identifiers, used by Alembic.
revision: str = '91222e284d25'
down_revision: Union[str, None] = 'e7cf957617be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_assumptions', sa.Column('assumption_type', sa.Enum('DATA_DERIVED', 'JUDGEMENT', 'USER_SUPPLIED', name='assumptiontype', native_enum=False), nullable=True))
    op.add_column('scenario_assumptions', sa.Column('range_min', sa.Float(), nullable=True))
    op.add_column('scenario_assumptions', sa.Column('range_max', sa.Float(), nullable=True))
    op.add_column('scenario_assumptions', sa.Column('source', sa.String(length=255), nullable=True))
    op.add_column('scenario_assumptions', sa.Column('confidence_basis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_assumptions', 'confidence_basis')
    op.drop_column('scenario_assumptions', 'source')
    op.drop_column('scenario_assumptions', 'range_max')
    op.drop_column('scenario_assumptions', 'range_min')
    op.drop_column('scenario_assumptions', 'assumption_type')
    # ### end Alembic commands ###
