"""initial_trace_schema

Revision ID: e7cf957617be
Revises: 
Create Date: 2026-09-28 18:06:50.224315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.app.models.base import GUID
import backend.app.models.base


# revision identifiers, used by Alembic.
revision: str = 'e7cf957617be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_settings_key'), 'application_settings', ['key'], unique=True)
    op.create_table('audit_events',
    sa.Column('event_type', sa.Enum('DATASET_UPLOADED', 'DATASET_PARSED', 'DATA_HEALTH_CHECK_COMPLETED', 'SCHEMA_MAPPED', 'DECISION_CREATED', 'INVESTIGATION_STARTED', 'CALCULATION_PRODUCED', 'VERIFICATION_COMPLETED', 'COUNTER_FINDING_RECORDED', 'SCENARIO_CHANGED', 'SANDBOX_MODIFIED', 'BRIEF_GENERATED', 'APPROVAL_SUBMITTED', 'DECISION_RECORD_CREATED', 'DECISION_REJECTED', 'LEDGER_OUTCOME_LOGGED', 'RATE_CARD_VERSION_CHANGED', name='auditaction', native_enum=False), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('datasets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_name'), 'datasets', ['name'], unique=False)
    op.create_table('decision_templates',
    sa.Column('template_code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_entities', sa.JSON(), nullable=False),
    sa.Column('required_metrics', sa.JSON(), nullable=False),
    sa.Column('default_assumptions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_templates_template_code'), 'decision_templates', ['template_code'], unique=True)
    op.create_table('documents',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('content_summary', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('job_type', sa.Enum('DATA_INGEST', 'DATA_HEALTH_CHECK', 'SEMANTIC_INFERENCE', 'INVESTIGATION_RUN', 'VERIFICATION_RUN', 'SCENARIO_SIMULATION', 'COUNTER_DECISION_RUN', 'UNDERWRITING_EVALUATION', 'LEDGER_RECALIBRATION', name='jobtype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('target_entity_type', sa.String(length=64), nullable=False),
    sa.Column('target_entity_id', backend.app.models.base.GUID(length=36), nullable=True),
    sa.Column('progress_stage', sa.String(length=128), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_target_entity_id'), 'jobs', ['target_entity_id'], unique=False)
    op.create_table('rate_cards',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recalibration_results',
    sa.Column('decision_class', sa.String(length=64), nullable=False),
    sa.Column('logged_decisions_count', sa.Integer(), nullable=False),
    sa.Column('claims_count', sa.Integer(), nullable=False),
    sa.Column('mean_error_ratio', sa.Float(), nullable=False),
    sa.Column('credibility_z', sa.Float(), nullable=False),
    sa.Column('experience_factor', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recalibration_results_decision_class'), 'recalibration_results', ['decision_class'], unique=False)
    op.create_table('data_transformations',
    sa.Column('dataset_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('transformation_type', sa.String(length=64), nullable=False),
    sa.Column('code_definition', sa.Text(), nullable=False),
    sa.Column('applied_by', sa.String(length=128), nullable=False),
    sa.Column('audit_provenance', sa.JSON(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_transformations_dataset_id'), 'data_transformations', ['dataset_id'], unique=False)
    op.create_table('dataset_files',
    sa.Column('dataset_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parse_metadata', sa.JSON(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_files_dataset_id'), 'dataset_files', ['dataset_id'], unique=False)
    op.create_table('decisions',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'INGESTING', 'AUDITING', 'INVESTIGATING', 'UNDERWRITTEN', 'APPROVED', 'MODIFIED', 'REJECTED', name='decisionstatus', native_enum=False), nullable=False),
    sa.Column('dataset_id', backend.app.models.base.GUID(length=36), nullable=True),
    sa.Column('template_id', backend.app.models.base.GUID(length=36), nullable=True),
    sa.Column('primary_metric_name', sa.String(length=128), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('validity_window_days', sa.Integer(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['decision_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_dataset_id'), 'decisions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_decisions_status'), 'decisions', ['status'], unique=False)
    op.create_index(op.f('ix_decisions_template_id'), 'decisions', ['template_id'], unique=False)
    op.create_index(op.f('ix_decisions_title'), 'decisions', ['title'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('metric_definitions',
    sa.Column('dataset_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('formula_expression', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('calculation_grain', sa.String(length=64), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_definitions_dataset_id'), 'metric_definitions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_metric_definitions_name'), 'metric_definitions', ['name'], unique=False)
    op.create_table('rate_card_versions',
    sa.Column('rate_card_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('version_str', sa.String(length=32), nullable=False),
    sa.Column('weight_data_quality', sa.Float(), nullable=False),
    sa.Column('weight_verification', sa.Float(), nullable=False),
    sa.Column('weight_contradiction', sa.Float(), nullable=False),
    sa.Column('base_model_uncertainty_weight', sa.Float(), nullable=False),
    sa.Column('band_recommended_max', sa.Float(), nullable=False),
    sa.Column('band_recommended_with_conditions_max', sa.Float(), nullable=False),
    sa.Column('band_refer_max', sa.Float(), nullable=False),
    sa.Column('tail_percentile', sa.Float(), nullable=False),
    sa.Column('policy_metadata', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rate_card_id'], ['rate_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_card_versions_rate_card_id'), 'rate_card_versions', ['rate_card_id'], unique=False)
    op.create_table('segment_definitions',
    sa.Column('dataset_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filter_criteria', sa.JSON(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('share_of_volume', sa.Float(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segment_definitions_dataset_id'), 'segment_definitions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_segment_definitions_name'), 'segment_definitions', ['name'], unique=False)
    op.create_table('approval_actions',
    sa.Column('decision_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'MODIFY', 'REJECT', name='approvalactiontype', native_enum=False), nullable=False),
    sa.Column('performed_by', sa.String(length=128), nullable=False),
    sa.Column('reason_or_notes', sa.Text(), nullable=True),
    sa.Column('sandbox_modifications', sa.JSON(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_actions_decision_id'), 'approval_actions', ['decision_id'], unique=False)
    op.create_table('assumptions',
    sa.Column('decision_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('assumption_type', sa.Enum('DATA_DERIVED', 'JUDGEMENT', 'USER_SUPPLIED', name='assumptiontype', native_enum=False), nullable=False),
    sa.Column('base_value', sa.Float(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('sensitivity_rank', sa.Integer(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assumptions_decision_id'), 'assumptions', ['decision_id'], unique=False)
    op.create_table('business_glossary_entries',
    sa.Column('term', sa.String(length=128), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('synonym_list', sa.JSON(), nullable=False),
    sa.Column('mapped_metric_id', backend.app.models.base.GUID(length=36), nullable=True),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mapped_metric_id'], ['metric_definitions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_glossary_entries_term'), 'business_glossary_entries', ['term'], unique=True)
    op.create_table('calculations',
    sa.Column('decision_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('formula_used', sa.Text(), nullable=False),
    sa.Column('result_numeric', sa.Float(), nullable=False),
    sa.Column('result_formatted', sa.String(length=64), nullable=False),
    sa.Column('input_parameters', sa.JSON(), nullable=False),
    sa.Column('input_row_count', sa.Integer(), nullable=False),
    sa.Column('code_provenance', sa.String(length=255), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculations_decision_id'), 'calculations', ['decision_id'], unique=False)
    op.create_index(op.f('ix_calculations_metric_name'), 'calculations', ['metric_name'], unique=False)
    op.create_table('counter_findings',
    sa.Column('decision_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('finding_text', sa.Text(), nullable=False),
    sa.Column('quantified_impact', sa.Float(), nullable=False),
    sa.Column('affected_segment', sa.String(length=128), nullable=True),
    sa.Column('evidence_reference', sa.String(length=255), nullable=True),
    sa.Column('is_absorbed_into_model', sa.Boolean(), nullable=False),
    sa.Column('unabsorbed_impact', sa.Float(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counter_findings_decision_id'), 'counter_findings', ['decision_id'], unique=False)
    op.create_table('dataset_tables',
    sa.Column('dataset_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('dataset_file_id', backend.app.models.base.GUID(length=36), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('raw_properties', sa.JSON(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_file_id'], ['dataset_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_tables_dataset_file_id'), 'dataset_tables', ['dataset_file_id'], unique=False)
    op.create_index(op.f('ix_dataset_tables_dataset_id'), 'dataset_tables', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_tables_name'), 'dataset_tables', ['name'], unique=False)
    op.create_table('decision_objectives',
    sa.Column('decision_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('primary_goal', sa.Text(), nullable=False),
    sa.Column('target_metric', sa.String(length=128), nullable=False),
    sa.Column('constraint_description', sa.Text(), nullable=True),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    op.create_table('investigation_plans',
    sa.Column('decision_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('plan_summary', sa.Text(), nullable=False),
    sa.Column('sufficiency_verdict', sa.Enum('SUFFICIENT', 'LIMITED', 'INSUFFICIENT', name='datasufficiencyverdict', native_enum=False), nullable=False),
    sa.Column('missing_information_rankings', sa.JSON(), nullable=False),
    sa.Column('stages_definition', sa.JSON(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_plans_decision_id'), 'investigation_plans', ['decision_id'], unique=False)
    op.create_table('investigation_runs',
    sa.Column('decision_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.String(length=64), nullable=True),
    sa.Column('completed_at', sa.String(length=64), nullable=True),
    sa.Column('execution_summary', sa.JSON(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_runs_decision_id'), 'investigation_runs', ['decision_id'], unique=False)
    op.create_table('loss_history_entries',
    sa.Column('decision_id', backend.app.models.base.GUID(length=36), nullable=True),
    sa.Column('decision_class', sa.String(length=64), nullable=False),
    sa.Column('decision_title', sa.String(length=255), nullable=False),
    sa.Column('underwritten_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validity_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('projected_upside', sa.Float(), nullable=False),
    sa.Column('decision_premium', sa.Float(), nullable=False),
    sa.Column('premium_rate', sa.Float(), nullable=False),
    sa.Column('p10_tail_exposure', sa.Float(), nullable=False),
    sa.Column('underwriting_verdict', sa.String(length=64), nullable=False),
    sa.Column('human_action', sa.String(length=32), nullable=False),
    sa.Column('actual_realised_value', sa.Float(), nullable=True),
    sa.Column('actual_vs_predicted_variance', sa.Float(), nullable=True),
    sa.Column('fell_inside_predicted_range', sa.Boolean(), nullable=True),
    sa.Column('lapse_event_triggered', sa.Boolean(), nullable=True),
    sa.Column('is_claim', sa.Boolean(), nullable=True, comment='True if outcome fell outside predicted range or lapse was triggered'),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loss_history_entries_decision_class'), 'loss_history_entries', ['decision_class'], unique=False)
    op.create_index(op.f('ix_loss_history_entries_decision_id'), 'loss_history_entries', ['decision_id'], unique=False)
    op.create_table('retrieval_records',
    sa.Column('decision_id', backend.app.models.base.GUID(length=36), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('matched_chunks_json', sa.JSON(), nullable=False),
    sa.Column('agent_role', sa.String(length=64), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_records_decision_id'), 'retrieval_records', ['decision_id'], unique=False)
    op.create_table('scenario_runs',
    sa.Column('decision_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('run_label', sa.String(length=128), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('is_sandbox', sa.Boolean(), nullable=False),
    sa.Column('simulation_count', sa.Integer(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_runs_decision_id'), 'scenario_runs', ['decision_id'], unique=False)
    op.create_table('coverage_lapse_conditions',
    sa.Column('decision_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('scenario_run_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('condition_type', sa.Enum('THRESHOLD', 'CONCENTRATION', 'DATA', 'DEFINITION', 'TIME', 'COMBINATION', name='lapseconditiontype', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metric_parameter_name', sa.String(length=128), nullable=False),
    sa.Column('current_modelled_value', sa.Float(), nullable=False),
    sa.Column('lapse_threshold_value', sa.Float(), nullable=False),
    sa.Column('distance_to_lapse_percent', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('is_breached', sa.Boolean(), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_run_id'], ['scenario_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverage_lapse_conditions_decision_id'), 'coverage_lapse_conditions', ['decision_id'], unique=False)
    op.create_index(op.f('ix_coverage_lapse_conditions_scenario_run_id'), 'coverage_lapse_conditions', ['scenario_run_id'], unique=False)
    op.create_table('dataset_columns',
    sa.Column('dataset_table_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('data_type', sa.String(length=64), nullable=False),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.Column('is_unique', sa.Boolean(), nullable=False),
    sa.Column('null_count', sa.Integer(), nullable=False),
    sa.Column('distinct_count', sa.Integer(), nullable=False),
    sa.Column('sample_values', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_table_id'], ['dataset_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_columns_dataset_table_id'), 'dataset_columns', ['dataset_table_id'], unique=False)
    op.create_table('decision_briefs',
    sa.Column('decision_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('scenario_run_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('brief_title', sa.String(length=255), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('sections_json', sa.JSON(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_run_id'], ['scenario_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    op.create_table('decision_premiums',
    sa.Column('decision_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('scenario_run_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('rate_card_version_id', backend.app.models.base.GUID(length=36), nullable=True),
    sa.Column('projected_upside', sa.Float(), nullable=False),
    sa.Column('expected_loss', sa.Float(), nullable=False),
    sa.Column('data_quality_load', sa.Float(), nullable=False),
    sa.Column('verification_load', sa.Float(), nullable=False),
    sa.Column('contradiction_load', sa.Float(), nullable=False),
    sa.Column('model_uncertainty_load', sa.Float(), nullable=False),
    sa.Column('total_risk_load', sa.Float(), nullable=False),
    sa.Column('total_decision_premium', sa.Float(), nullable=False),
    sa.Column('premium_rate', sa.Float(), nullable=False),
    sa.Column('expected_net_benefit', sa.Float(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rate_card_version_id'], ['rate_card_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_run_id'], ['scenario_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_run_id')
    )
    op.create_index(op.f('ix_decision_premiums_decision_id'), 'decision_premiums', ['decision_id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('decision_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('statement_text', sa.Text(), nullable=False),
    sa.Column('statement_level', sa.Enum('OBSERVED_FACT', 'CALCULATED_RESULT', 'MODELLED_SCENARIO', 'RECOMMENDATION', name='statementlevel', native_enum=False), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=True),
    sa.Column('calculation_id', backend.app.models.base.GUID(length=36), nullable=True),
    sa.Column('source_table_name', sa.String(length=128), nullable=True),
    sa.Column('row_count_sample', sa.Integer(), nullable=True),
    sa.Column('is_contradiction', sa.Boolean(), nullable=False),
    sa.Column('provenance_metadata', sa.JSON(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_decision_id'), 'evidence_items', ['decision_id'], unique=False)
    op.create_table('exposure_reports',
    sa.Column('decision_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('scenario_run_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('probability_of_net_loss', sa.Float(), nullable=False),
    sa.Column('downside_at_tail', sa.Float(), nullable=False),
    sa.Column('worst_plausible_case_loss', sa.Float(), nullable=False),
    sa.Column('worst_plausible_assumptions', sa.JSON(), nullable=False),
    sa.Column('concentration_exposure_amount', sa.Float(), nullable=False),
    sa.Column('concentration_account_count', sa.Integer(), nullable=False),
    sa.Column('concentration_volume_share', sa.Float(), nullable=False),
    sa.Column('data_exposure_min', sa.Float(), nullable=False),
    sa.Column('data_exposure_max', sa.Float(), nullable=False),
    sa.Column('adverse_finding_exposure_total', sa.Float(), nullable=False),
    sa.Column('cost_of_inaction', sa.Float(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_run_id'], ['scenario_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_run_id')
    )
    op.create_index(op.f('ix_exposure_reports_decision_id'), 'exposure_reports', ['decision_id'], unique=False)
    op.create_table('investigation_questions',
    sa.Column('investigation_plan_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('target_agent', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_plan_id'], ['investigation_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_questions_investigation_plan_id'), 'investigation_questions', ['investigation_plan_id'], unique=False)
    op.create_table('outcome_records',
    sa.Column('loss_history_entry_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('logged_by', sa.String(length=128), nullable=False),
    sa.Column('outcome_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('primary_metric_realised', sa.Float(), nullable=False),
    sa.Column('variance_notes', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['loss_history_entry_id'], ['loss_history_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcome_records_loss_history_entry_id'), 'outcome_records', ['loss_history_entry_id'], unique=False)
    op.create_table('scenario_assumptions',
    sa.Column('scenario_run_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('parameter_name', sa.String(length=128), nullable=False),
    sa.Column('parameter_value', sa.Float(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('is_modified_in_sandbox', sa.Boolean(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_run_id'], ['scenario_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_assumptions_scenario_run_id'), 'scenario_assumptions', ['scenario_run_id'], unique=False)
    op.create_table('scenario_results',
    sa.Column('scenario_run_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('projected_upside', sa.Float(), nullable=False),
    sa.Column('expected_loss', sa.Float(), nullable=False),
    sa.Column('p10_tail_outcome', sa.Float(), nullable=False),
    sa.Column('tail_average_loss', sa.Float(), nullable=False),
    sa.Column('worst_plausible_loss', sa.Float(), nullable=False),
    sa.Column('probability_of_net_loss', sa.Float(), nullable=False),
    sa.Column('cost_of_inaction', sa.Float(), nullable=False),
    sa.Column('distribution_quantiles', sa.JSON(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_run_id'], ['scenario_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_run_id')
    )
    op.create_table('semantic_entities',
    sa.Column('dataset_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('entity_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_table_id', backend.app.models.base.GUID(length=36), nullable=True),
    sa.Column('identifier_column', sa.String(length=128), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_table_id'], ['dataset_tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_entities_dataset_id'), 'semantic_entities', ['dataset_id'], unique=False)
    op.create_table('underwriting_verdicts',
    sa.Column('decision_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('scenario_run_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('verdict', sa.Enum('RECOMMENDED', 'RECOMMENDED_WITH_CONDITIONS', 'REFER', 'DECLINE', name='underwritingverdicttype', native_enum=False), nullable=False),
    sa.Column('summary_sentence', sa.Text(), nullable=False),
    sa.Column('conditions_list', sa.JSON(), nullable=False),
    sa.Column('exclusions_list', sa.JSON(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_run_id'], ['scenario_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_run_id')
    )
    op.create_index(op.f('ix_underwriting_verdicts_decision_id'), 'underwriting_verdicts', ['decision_id'], unique=False)
    op.create_table('verification_results',
    sa.Column('calculation_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('method_primary_name', sa.String(length=128), nullable=False),
    sa.Column('method_secondary_name', sa.String(length=128), nullable=False),
    sa.Column('method_primary_value', sa.Float(), nullable=False),
    sa.Column('method_secondary_value', sa.Float(), nullable=False),
    sa.Column('absolute_discrepancy', sa.Float(), nullable=False),
    sa.Column('relative_discrepancy', sa.Float(), nullable=False),
    sa.Column('tolerance_threshold', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_results_calculation_id'), 'verification_results', ['calculation_id'], unique=False)
    op.create_table('data_quality_findings',
    sa.Column('dataset_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('dataset_table_id', backend.app.models.base.GUID(length=36), nullable=True),
    sa.Column('dataset_column_id', backend.app.models.base.GUID(length=36), nullable=True),
    sa.Column('finding_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='dataqualityseverity', native_enum=False), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('affected_rows_count', sa.Integer(), nullable=False),
    sa.Column('affected_ratio', sa.Float(), nullable=False),
    sa.Column('proposed_treatment', sa.String(length=255), nullable=True),
    sa.Column('effect_on_premium_load', sa.Float(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_column_id'], ['dataset_columns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_table_id'], ['dataset_tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_findings_dataset_id'), 'data_quality_findings', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_data_quality_findings_finding_type'), 'data_quality_findings', ['finding_type'], unique=False)
    op.create_table('decision_records',
    sa.Column('decision_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('decision_brief_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('approver_name', sa.String(length=128), nullable=False),
    sa.Column('approver_role', sa.String(length=128), nullable=False),
    sa.Column('action_type', sa.Enum('APPROVE', 'MODIFY', 'REJECT', name='approvalactiontype', native_enum=False), nullable=False),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('is_immutable', sa.Boolean(), nullable=False),
    sa.Column('brief_snapshot', sa.JSON(), nullable=False),
    sa.Column('evidence_chain_snapshot', sa.JSON(), nullable=False),
    sa.Column('rate_card_snapshot', sa.JSON(), nullable=False),
    sa.Column('modifications_made', sa.JSON(), nullable=True),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_brief_id'], ['decision_briefs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_records_decision_brief_id'), 'decision_records', ['decision_brief_id'], unique=False)
    op.create_index(op.f('ix_decision_records_decision_id'), 'decision_records', ['decision_id'], unique=False)
    op.create_table('semantic_relationships',
    sa.Column('dataset_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('source_entity_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('target_entity_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('foreign_key_column', sa.String(length=128), nullable=True),
    sa.Column('cardinality', sa.String(length=32), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['semantic_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['semantic_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_relationships_dataset_id'), 'semantic_relationships', ['dataset_id'], unique=False)
    op.create_table('tripwires',
    sa.Column('coverage_lapse_condition_id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('alert_threshold', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('review_cadence', sa.String(length=64), nullable=False),
    sa.Column('is_triggered', sa.Boolean(), nullable=False),
    sa.Column('id', backend.app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coverage_lapse_condition_id'], ['coverage_lapse_conditions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tripwires_coverage_lapse_condition_id'), 'tripwires', ['coverage_lapse_condition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tripwires_coverage_lapse_condition_id'), table_name='tripwires')
    op.drop_table('tripwires')
    op.drop_index(op.f('ix_semantic_relationships_dataset_id'), table_name='semantic_relationships')
    op.drop_table('semantic_relationships')
    op.drop_index(op.f('ix_decision_records_decision_id'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_decision_brief_id'), table_name='decision_records')
    op.drop_table('decision_records')
    op.drop_index(op.f('ix_data_quality_findings_finding_type'), table_name='data_quality_findings')
    op.drop_index(op.f('ix_data_quality_findings_dataset_id'), table_name='data_quality_findings')
    op.drop_table('data_quality_findings')
    op.drop_index(op.f('ix_verification_results_calculation_id'), table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_index(op.f('ix_underwriting_verdicts_decision_id'), table_name='underwriting_verdicts')
    op.drop_table('underwriting_verdicts')
    op.drop_index(op.f('ix_semantic_entities_dataset_id'), table_name='semantic_entities')
    op.drop_table('semantic_entities')
    op.drop_table('scenario_results')
    op.drop_index(op.f('ix_scenario_assumptions_scenario_run_id'), table_name='scenario_assumptions')
    op.drop_table('scenario_assumptions')
    op.drop_index(op.f('ix_outcome_records_loss_history_entry_id'), table_name='outcome_records')
    op.drop_table('outcome_records')
    op.drop_index(op.f('ix_investigation_questions_investigation_plan_id'), table_name='investigation_questions')
    op.drop_table('investigation_questions')
    op.drop_index(op.f('ix_exposure_reports_decision_id'), table_name='exposure_reports')
    op.drop_table('exposure_reports')
    op.drop_index(op.f('ix_evidence_items_decision_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_decision_premiums_decision_id'), table_name='decision_premiums')
    op.drop_table('decision_premiums')
    op.drop_table('decision_briefs')
    op.drop_index(op.f('ix_dataset_columns_dataset_table_id'), table_name='dataset_columns')
    op.drop_table('dataset_columns')
    op.drop_index(op.f('ix_coverage_lapse_conditions_scenario_run_id'), table_name='coverage_lapse_conditions')
    op.drop_index(op.f('ix_coverage_lapse_conditions_decision_id'), table_name='coverage_lapse_conditions')
    op.drop_table('coverage_lapse_conditions')
    op.drop_index(op.f('ix_scenario_runs_decision_id'), table_name='scenario_runs')
    op.drop_table('scenario_runs')
    op.drop_index(op.f('ix_retrieval_records_decision_id'), table_name='retrieval_records')
    op.drop_table('retrieval_records')
    op.drop_index(op.f('ix_loss_history_entries_decision_id'), table_name='loss_history_entries')
    op.drop_index(op.f('ix_loss_history_entries_decision_class'), table_name='loss_history_entries')
    op.drop_table('loss_history_entries')
    op.drop_index(op.f('ix_investigation_runs_decision_id'), table_name='investigation_runs')
    op.drop_table('investigation_runs')
    op.drop_index(op.f('ix_investigation_plans_decision_id'), table_name='investigation_plans')
    op.drop_table('investigation_plans')
    op.drop_table('decision_objectives')
    op.drop_index(op.f('ix_dataset_tables_name'), table_name='dataset_tables')
    op.drop_index(op.f('ix_dataset_tables_dataset_id'), table_name='dataset_tables')
    op.drop_index(op.f('ix_dataset_tables_dataset_file_id'), table_name='dataset_tables')
    op.drop_table('dataset_tables')
    op.drop_index(op.f('ix_counter_findings_decision_id'), table_name='counter_findings')
    op.drop_table('counter_findings')
    op.drop_index(op.f('ix_calculations_metric_name'), table_name='calculations')
    op.drop_index(op.f('ix_calculations_decision_id'), table_name='calculations')
    op.drop_table('calculations')
    op.drop_index(op.f('ix_business_glossary_entries_term'), table_name='business_glossary_entries')
    op.drop_table('business_glossary_entries')
    op.drop_index(op.f('ix_assumptions_decision_id'), table_name='assumptions')
    op.drop_table('assumptions')
    op.drop_index(op.f('ix_approval_actions_decision_id'), table_name='approval_actions')
    op.drop_table('approval_actions')
    op.drop_index(op.f('ix_segment_definitions_name'), table_name='segment_definitions')
    op.drop_index(op.f('ix_segment_definitions_dataset_id'), table_name='segment_definitions')
    op.drop_table('segment_definitions')
    op.drop_index(op.f('ix_rate_card_versions_rate_card_id'), table_name='rate_card_versions')
    op.drop_table('rate_card_versions')
    op.drop_index(op.f('ix_metric_definitions_name'), table_name='metric_definitions')
    op.drop_index(op.f('ix_metric_definitions_dataset_id'), table_name='metric_definitions')
    op.drop_table('metric_definitions')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_decisions_title'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_template_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_status'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_dataset_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_dataset_files_dataset_id'), table_name='dataset_files')
    op.drop_table('dataset_files')
    op.drop_index(op.f('ix_data_transformations_dataset_id'), table_name='data_transformations')
    op.drop_table('data_transformations')
    op.drop_index(op.f('ix_recalibration_results_decision_class'), table_name='recalibration_results')
    op.drop_table('recalibration_results')
    op.drop_table('rate_cards')
    op.drop_index(op.f('ix_jobs_target_entity_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('documents')
    op.drop_index(op.f('ix_decision_templates_template_code'), table_name='decision_templates')
    op.drop_table('decision_templates')
    op.drop_index(op.f('ix_datasets_name'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_application_settings_key'), table_name='application_settings')
    op.drop_table('application_settings')
    # ### end Alembic commands ###
